# These are supported funding model platforms

github: lorron
patreon: lorron
open_collective: lorron
ko_fi: lorron
tidelift: lorron/electron-vue-rtc
community_bridge: electron-vue-rtc
liberapay: lorron
issuehunt: lorron
otechie: lorron
custom: lorron
